FROM nvidia/cuda:7.5-cudnn4-runtime
RUN ln -s /usr/lib/x86_64-linux-gnu/libcudnn.so.4 /usr/lib/x86_64-linux-gnu/libcudnn.so
RUN echo '\
    deb http://archive.ubuntu.com/ubuntu/ trusty main\n\
    deb http://archive.ubuntu.com/ubuntu/ trusty universe\n\
    deb http://archive.ubuntu.com/ubuntu/ trusty-updates main\n'\
    > /etc/apt/sources.list
RUN apt-get update && apt-get install --no-install-recommends -y \
        gcc \
        libopenblas-base \
        libzookeeper-mt-dev \
        ca-certificates \
        python-dev \
        git-core && \
    apt-get autoremove --purge -y && \
    apt-get clean
RUN apt-get install nvidia-modprobe
# add libcuda sos
ADD usr/lib/libcuda.so /usr/local/nvidia/lib/libcuda.so
ADD usr/lib/libcuda.so.1 /usr/local/nvidia/lib/libcuda.so.1
ADD usr/lib/libcuda.so.361.42 /usr/local/nvidia/lib/libcuda.so.361.42
ADD usr/lib64/libcuda.so /usr/local/nvidia/lib64/libcuda.so
ADD usr/lib64/libcuda.so.1 /usr/local/nvidia/lib64/libcuda.so.1
ADD usr/lib64/libcuda.so.361.42 /usr/local/nvidia/lib64/libcuda.so.361.42


RUN python -c 'import urllib2;exec(urllib2.urlopen("https://bootstrap.pypa.io/get-pip.py").read())' --no-cache-dir --timeout 1000
pip install --no-cache-dir --timeout 1000 -r "https://raw.githubusercontent.com/tjsongzw/tfmesos/test/requirements_gpu.txt"
ADD . /tfmesos
RUN pip install /tfmesos/.
ENV DOCKER_IMAGE tfmesos/tfmesos:gpu
